routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

$this->group(['middleware' => 'auth'], function () {
    $this->get('/', 'DashboardController@index')->name('dashboard');

    $this->resources([
        'domains' => 'DomainController',
        'links' => 'LinkController'
    ]);
});

app/Domain.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Domain extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'have_sitemap',
        'sitemap_url',
        'type_skan',
        'keywords',
        'regular_price_query',
        'price_file_url',
        'relation_file_url'
    ];

    public static function typesSkan()
    {
        return [
            1 => 'Sitemap',
            2 => 'XML-file',
            3 => 'Not skan',
            4 => 'Without sitemap',
        ];
    }

    public static function getTypeSkan($value)
    {
        $types = self::typesSkan();
        if (isset($types[$value])) {
            return $types[$value];
        }
        return '';
    }
}

app/Link.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard');
    }
}

app/Http/Controllers/DomainController.php
<?php

namespace App\Http\Controllers;

use App\Domain;
use Illuminate\Http\Request;

class DomainController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $domains = Domain::paginate(20);
        return view('domain.index', compact('domains'))->with('i', (request()->input('page', 1) -1)*50);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validateDomain($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function show(Domain $domain)
    {
        return view('domain.show', compact('domain'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function edit(Domain $domain)
    {
        return view('domain.edit', compact('domain'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Domain $domain)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function destroy(Domain $domain)
    {
        //
    }

    /**
     * Validate the save domain request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return void
     */
    protected function validateDomain(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'sitemap_url' => 'string|max:255',
            'type_skan' => 'required|integer',
            'keywords' => 'string|max:10000',
            'regular_price_query' => 'string|max:255',
            'price_file_url' => 'string|max:255',
            'relation_file_url' => 'string|max:255',
        ]);
    }
}

app/Http/Controllers/LinkController.php
<?php

namespace App\Http\Controllers;

use App\Link;
use Illuminate\Http\Request;

class LinkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Link  $link
     * @return \Illuminate\Http\Response
     */
    public function show(Link $link)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Link  $link
     * @return \Illuminate\Http\Response
     */
    public function edit(Link $link)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Link  $link
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Link $link)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Link  $link
     * @return \Illuminate\Http\Response
     */
    public function destroy(Link $link)
    {
        //
    }
}

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/domain/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid"></div>
@endsection

resources/views/domain/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <h5>Редактирование домена {{$domain->name}}</h5>
        <hr>
        <div class="row">
            <div class="card border-0 rounded-0 w-100">
                <div class="card-body">
                    <form action="{{route('domains.update', $domain->id)}}" method="@method('PUT')">
                        {{csrf_field()}}
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label text-nowrap" for="name">Название</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control rounded-0" id="name" name="name" value="{{$domain->name}}" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label text-nowrap" for="keywords">Ключевые слова</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control rounded-0" id="keywords" name="keywords" value="{{$domain->keywords}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label text-nowrap" for="sitemap_url">Адрес карты сайта</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control rounded-0" id="sitemap_url" name="sitemap_url" value="{{$domain->sitemap_url}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label text-nowrap" for="regular_price_query">Регулярное выражение</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control rounded-0" id="regular_price_query" name="regular_price_query" value="{{$domain->regular_price_query}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label text-nowrap" for="price_file_url">Путь к прайсу</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control rounded-0" id="price_file_url" name="price_file_url" value="{{$domain->price_file_url}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label text-nowrap" for="relation_file_url">Путь к связям</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control rounded-0" id="relation_file_url" name="relation_file_url" value="{{$domain->relation_file_url}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label text-nowrap" for="type_skan">Тип сканирования</label>
                            <div class="col-sm-9">
                                <select class="form-control rounded-0" id="type_skan" name="type_skan">
                                    @foreach(\App\Domain::typesSkan() as $key => $value)
                                        <option value="{{$key}}" @if ($domain->type_skan == $key) selected @endif>{{$value}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label text-nowrap" for="created_at">Добавлен</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control rounded-0" id="created_at" value="{{$domain->created_at}}" disabled>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label text-nowrap" for="date_skan">Дата парсинга</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control rounded-0" id="date_skan" value="{{$domain->date_skan}}" disabled>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label text-nowrap" for="status">Статус</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control rounded-0" id="status" value="{{$domain->status}}" disabled>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9">
                                <button type="submit" class="btn btn-primary rounded-0">Сохранить</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/domain/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <h3>Домены</h3>
        <hr>
        <div class="row">
            <div class="card border-0 rounded-0 w-100">
                <div class="card-body">
                    <table class="table table-sm table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th>ID</th>
                                <th>Название</th>
                                <th>Кол. ссылок</th>
                                <th>Кол. связей</th>
                                <th>Карта сайта</th>
                                <th>Тип скана</th>
                                <th>Регулярное выражение</th>
                                <th>Путь к прайсу</th>
                                <th>Дата парсинга</th>
                                <th>Статус</th>
                                <th>Загрузка</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($domains as $domain)
                            <tr>
                                <td>{{$domain->id}}</td>
                                <td>{{$domain->name}}</td>
                                <td></td>
                                <td></td>
                                <td class="text-center">
                                    @if ($domain->have_sitemap) <i class="fas fa-check"></i> @else <i class="fas fa-times"></i> @endif
                                </td>
                                <td>{{App\Domain::getTypeSkan($domain->type_skan)}}</td>
                                <td class="text-center">
                                    @if ($domain->regular_price_query) <i class="fas fa-check"></i> @else <i class="fas fa-times"></i> @endif
                                </td>
                                <td class="text-center">
                                    @if ($domain->price_file_url) <i class="fas fa-check"></i> @else <i class="fas fa-times"></i> @endif
                                </td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td class="action-column edit"><a href="{{route('domains.edit', $domain->id)}}"><i class="fas fa-pencil-alt"></i></a></td>
                                <td class="action-column remove">
                                    <form action="{{ route('domains.destroy', $domain->id) }}" method="@method('DESTROY')">
                                        {{ csrf_field() }}
                                        <button type="submit"><i class="fas fa-trash-alt"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer d-flex justify-content-center">
                    {!! $domains->links() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/domain/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid"></div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    {{--<link href="{{ asset('css/app.css') }}" rel="stylesheet">--}}
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/common.css') }}" rel="stylesheet">
    <link href="{{ asset('css/sidebar.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>

<div class="page-wrapper chiller-theme toggled">
    <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
        <i class="fas fa-bars"></i>
    </a>
    <nav id="sidebar" class="sidebar-wrapper">
        <div class="sidebar-content">
            <div class="sidebar-brand">
                <a href="#">tyre parser</a>
                <div id="close-sidebar">
                    <i class="fas fa-times"></i>
                </div>
            </div>
            <div class="sidebar-header">
                <div class="user-pic">
                    <img class="img-responsive img-rounded"
                         src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                         alt="User picture">
                </div>
                <div class="user-info">
                    <span class="user-name">{{Auth::user()->username}}</span>
                    <span class="user-role">Администратор</span>
                    <span class="user-status">
                        <i class="fa fa-circle"></i>
                        <span>Online</span>
                    </span>
                </div>
            </div>
            <!-- sidebar-header  -->
            <div class="sidebar-search">
                <div>
                    <div class="input-group">
                        <input type="text" class="form-control search-menu" placeholder="Поиск...">
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- sidebar-search  -->
            <div class="sidebar-menu">
                <ul>
                    <li class="header-menu">
                        <span>Основные</span>
                    </li>
                    {{--<li class="sidebar-dropdown">--}}
                    {{--<a href="#">--}}
                    {{--<i class="fa fa-tachometer-alt"></i>--}}
                    {{--<span>Dashboard</span>--}}
                    {{--</a>--}}
                    {{--<div class="sidebar-submenu">--}}
                    {{--<ul>--}}
                    {{--<li>--}}
                    {{--<a href="#">Dashboard 1</a>--}}
                    {{--</li>--}}
                    {{--<li>--}}
                    {{--<a href="#">Dashboard 2</a>--}}
                    {{--</li>--}}
                    {{--<li>--}}
                    {{--<a href="#">Dashboard 3</a>--}}
                    {{--</li>--}}
                    {{--</ul>--}}
                    {{--</div>--}}
                    {{--</li>--}}
                    <li class="@if (Route::currentRouteName() == 'dashboard') active @endif">
                        <a href="{{route('dashboard')}}">
                            <i class="fa fa-tachometer-alt"></i>
                            <span>Главная</span>
                        </a>
                    </li>
                    <li class="@if (Route::currentRouteName() == 'domains.index') active @endif">
                        <a href="{{route('domains.index')}}">
                            <i class="fa fa-folder"></i>
                            <span>Домены</span>
                        </a>
                    </li>
                    <li class="@if (Route::currentRouteName() == 'links.index') active @endif">
                        <a href="{{route('links.index')}}">
                            <i class="fa fa-book"></i>
                            <span>Ссылки</span>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- sidebar-menu  -->
        </div>
        <!-- sidebar-content  -->
        <div class="sidebar-footer">
            <a href="{{ route('logout') }}"
               onclick="event.preventDefault();document.getElementById('logout-form').submit();">Выйти</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST"
                  style="display: none;">
                {{ csrf_field() }}
            </form>
        </div>
    </nav>
    <!-- sidebar-wrapper  -->
    <main class="page-content">
        @yield('content')
    </main>
    <!-- page-content" -->
</div>

<!-- Scripts -->
<script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/sidebar.js') }}"></script>
</body>
</html>

resources/views/link/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid"></div>
@endsection

resources/views/link/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid"></div>
@endsection

resources/views/link/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid"></div>
@endsection

resources/views/link/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid"></div>
@endsection